# Generated by Django 4.2.7 on 2023-12-01 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0003_alter_order_amount_alter_order_crypto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="capacity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="exchange_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "crypto")},
        ),
    ]
