# Generated by Django 4.2.7 on 2023-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_alter_crypto_capacity_alter_crypto_exchange_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="desired_exchange_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
