# Generated by Django 4.2.7 on 2023-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_order_execution_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField()),
                ("crypto_name", models.CharField()),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
    ]
