# Generated by Django 4.2.7 on 2023-12-13 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0007_transaction_alter_order_is_auto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="History",
        ),
    ]
