# Generated by Django 4.2.8 on 2023-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0008_rename_transaction_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="code",
            field=models.CharField(default="BTC", unique=True),
            preserve_default=False,
        ),
    ]
