# Generated by Django 4.2.8 on 2023-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0009_crypto_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="exchange_rate",
            field=models.FloatField(default=14500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="execution_method",
            field=models.CharField(default="Price", max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="order_type",
            field=models.CharField(default="Sale", max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="amount",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="total_price",
            field=models.FloatField(default=445),
            preserve_default=False,
        ),
    ]
